apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: naser1945.bp@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - 'naser.cloud'
            - 'snaya.org'
        dns01:
          cloudflare:
            email: naser1945.bp@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
