apiVersion: platform.snaya.org/v1alpha1
kind: PGCluster
metadata:
  name: hakaya-dev-db
  namespace: hakaya-dev
spec:
  namespace: hakaya-dev
  databaseName: hakaya-dev
  clusterName: hakaya-dev-db-1
  sourceServerName: hakaya-dev-db
  secretName: hakaya-dev-secrets
