apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-cluster-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authentik-cluster-user
