apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik

spec:
  instances: 1
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-cluster-user
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: r2-db-store

  storage:
    size: 1Gi
