apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-shared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/newer97/k3d
    targetRevision: master
    path: src/apps/crossplane-shared/
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
