apiVersion: v1

kind: Secret

metadata:
  name: wireguard
  namespace: wireguard

type: Opaque

stringData:
  wg0.conf.template: |
    [Interface]
    Address = 172.16.16.0/20
    ListenPort = 51820
    PrivateKey = AGoxsjDofZrYrdN80nSP1XhlXTcSEzJ1uZbQnehMdWM=
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ENI -j MASQUERADE
    PostUp = sysctl -w -q net.ipv4.ip_forward=1
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ENI -j MASQUERADE
    PostDown = sysctl -w -q net.ipv4.ip_forward=0

    [Peer]
    PublicKey = nVbnwyh3NuUhP4ZlcAcUITu5s8hiC33bJWvlE3NNPkc=
    AllowedIPs = 192.168.1.0/24
