apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsecrets.platform.snaya.org
  labels:
    provider: generic
spec:
  compositeTypeRef:
    apiVersion: platform.snaya.org/v1alpha1
    kind: XSecret
  mode: Pipeline
  pipeline:
    - step: validate-input
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLRun
        metadata:
          name: validation
        spec:
          source: |
            oxr = option("params").oxr
            spec = oxr.spec

            bannedKeys = ["root", "admin", "password"]

            _items = [] # Initialize items list for results

            if spec.secretKey in bannedKeys:
                _items = _items + [
                    Result {
                        severity = "fatal"
                        message = "Secret key '%(spec.secretKey)' is banned." % {spec: spec}
                    }
                ]

            if len(spec.secretValue) < 6:
                _items = _items + [
                    Result {
                        severity = "fatal"
                        message = "Secret value must be at least 6 characters long."
                    }
                ]
            items = _items
    - step: create-secret
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLRun
        metadata:
          name: secret-creation
        spec:
          source: |
            # secret-creation.k content goes here
            oxr = option("params").oxr
            spec = oxr.spec
            dxr = option("params").dxr

            encodedSecretValue = base64.encode(spec.secretValue)

            generatedSecrets = []

            for i in range(spec.numberOfSecrets) {
                secretName = spec.secretName
                if spec.numberOfSecrets > 1 {
                    secretName = "$(spec.secretName)-$(i)"
                }

                secret = {
                    apiVersion = "v1"
                    kind = "Secret"
                    metadata.namespace = spec.namespace
                    metadata.name = secretName
                    metadata.annotations: {
                        "krm.kcl.dev/composition-resource-name" = "secret-$(i)"
                    }
                    type = "Opaque"
                    data: {
                        (spec.secretKey): encodedSecretValue
                    }
                }
                _ = generatedSecrets.append(secret)
            }
            items = generatedSecrets + [dxr] # Pass through dxr for readiness
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
