apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsecrets.platform.snaya.org
  labels:
    provider: generic
spec:
  compositeTypeRef:
    apiVersion: platform.snaya.org/v1alpha1
    kind: XSecret
  mode: Pipeline
  pipeline:
    - step: validate-input
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLRun
        metadata:
          name: validation
        spec:
          source: |
            oxr = option("params").oxr
            spec = oxr.spec

            bannedKeys = ["root", "admin", "password"]

            if spec.secretKey in bannedKeys:
                assert False, "Secret key " + spec.secretKey + " is banned."

            if len(spec.secretValue) < 6:
                assert False, "Secret value must be at least 6 characters long."
    - step: create-secret
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLRun
        metadata:
          name: secret-creation
        spec:
          source: |
            # secret-creation.k content goes here
            import base64
            oxr = option("params").oxr
            spec = oxr.spec
            dxr = option("params").dxr

            encodedSecretValue = base64.encode(spec.secretValue)

            generatedSecrets = [{
                apiVersion = "v1"
                kind = "Secret"
                metadata.namespace = spec.namespace
                metadata.name = "$(spec.secretName)-$(i)"
                metadata.annotations: {
                    "krm.kcl.dev/composition-resource-name" = "secret-$(i)"
                }
                type = "Opaque"
                data: {
                    (spec.secretKey): encodedSecretValue
                }
            } for i in range(spec.numberOfSecrets)]

            items = generatedSecrets + [dxr] # Pass through dxr for readiness
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
