apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'cert-manager,external-dns'
  dataFrom:
    - extract:
        key: cf-token-api
