apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-db-backup-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
  dataFrom:
    - extract:
        key: r2-db-backup-credentials
